name: marta_teknoloji_case
description: Simple Weather App.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Stacked
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  #Network
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1
  #Service Locator
  get_it: ^7.6.4
  #Caching
  hive_flutter: ^1.1.0
  #Utility
  dartz: ^0.10.1
  envied: ^0.3.0+3
  geolocator: ^10.1.0
  app_settings: ^5.1.1
  #Json Parsing
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Code Gen
  build_runner: ^2.4.5
  stacked_generator: ^1.3.3
  envied_generator: ^0.3.0+3
  #Json Parsing
  json_serializable: ^6.7.1
  #Linter
  flutter_lints: ^2.0.0
  #Test
  mockito: ^5.4.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
